return {
    --[Normal Ranks Wanderer to Diamond Citizen]--
    ['wanderer'] = {  --[ Wanderer]--
    rank = 'Wanderer',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-4 icr-data',
    backgroundstyle = 'icr-WandererBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['citizen'] = {  --[ Citizen ]--
    rank = 'Citizen',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-1 icr-data',
    backgroundstyle = 'icr-CitizenBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['trusted'] = {  --[ Gold Citizen ]--
    rank = 'Gold Citizen',
    bracketstyle = 'icr-t-6 icr-data',
    rankstyle = 'icr-t-a icr-data',
    backgroundstyle = 'icr-TrustedBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['diamondcitizen'] = {  --[ Diamond Citizen ]--
    rank = 'Diamond Citizen',
    bracketstyle = 'icr-t-b icr-data',
    rankstyle = 'icr-t-a icr-data',
    backgroundstyle = 'icr-DiamondCitizenBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    --[Donation Ranks Hero to Donator++]--
    ['hero'] = {  --[ Hero ]--
    rank = 'Hero',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-2 icr-data',
    backgroundstyle = 'icr-HeroBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['legend'] = {  --[ Legend ]--
    rank = 'Legend',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-9 icr-data',
    backgroundstyle = 'icr-LegendBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['mystic'] = {  --[ Mystic ]--
    rank = 'Mystic',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-b icr-data',
    backgroundstyle = 'icr-MysticBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['donator'] = {  --[ Donator ]--
    rank = 'Donator',
    bracketstyle = 'icr-t-8 icr-data',
    rankstyle = 'icr-t-c icr-data',
    backgroundstyle = 'icr-DonatorBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['donatorplus'] = {  --[ Donator+ ]--
    rank = 'Donator',
    bracketstyle = 'icr-t-8 icr-data',
    rankstyle = 'icr-t-c icr-data',
    backgroundstyle = 'icr-DonatorPlusBodyStyle',
    plus='+',
    plusstyle='icr-t-4 icr-data',
 },
    ['donatorplusplus'] = {  --[ Donator++ ]--
    rank = 'Donator',
    bracketstyle = 'icr-t-8 icr-data',
    rankstyle = 'icr-t-c icr-data',
    backgroundstyle = 'icr-DonatorPlusPlusBodyStyle',
    plus='++',
    plusstyle='icr-t-4 icr-data',
 },
 --[Staff Ranks Trial to Admin]--
    ['trial'] = {  --[ Trial Helper ]--
    rank = 'Trial Helper',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-a icr-data',
    backgroundstyle = 'icr-TrialBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['helper'] = {  --[ Helper ]--
    rank = 'Helper',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-3 icr-data',
    backgroundstyle = 'icr-HelperBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['moderator'] = {  --[ Moderator ]--
    rank = 'Moderator',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-6 icr-data',
    backgroundstyle = 'icr-ModeratorBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['admin'] = {  --[ Admin ]--
    rank = 'Admin',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-4 icr-data',
    backgroundstyle = 'icr-AdminBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
--[Developer and Infrastructure ranks]--
    ['developer'] = {  --[ Developer ]--
    rank = 'Developer',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-c icr-data',
    backgroundstyle = 'icr-DeveloperBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
    ['infrastructure'] = {  --[ Infrastructure ]--
    rank = 'Infrastructure',
    bracketstyle = 'icr-t-f icr-data',
    rankstyle = 'icr-t-6 icr-data',
    backgroundstyle = 'icr-InfrastructureBodyStyle',
    plus='',
    plusstyle='icr-t-4 icr-data',
 },
}
